<a href="https://colab.research.google.com/github/samikshalokhande/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [175]:
#import numpy
import numpy as np
import numpy 
from numpy import *

In [148]:
#numpy takes less memory than list
import sys
list1 = range(1000)
list1
print("Size of list = "+str(sys.getsizeof(len(list1))))
print("Size of list *5 = "+str(sys.getsizeof(5)*(len(list1))))
print("-----------------")
num_arr = np.arange(1000)
print("Size of num_arr = "+str(num_arr.size))
print("Size of num_arr = "+str(num_arr.size*5))
print("Size of num_arr *1000= "+str(num_arr.size*num_arr.itemsize))
#size of numpy arr is smaller than list

Size of list = 28
Size of list *5 = 28000
-----------------
Size of num_arr = 1000
Size of num_arr = 5000
Size of num_arr *1000= 8000


In [149]:
#numpy array is faster than list
import time
x=300000
l1= range(x)
l2= range(x)

x1= np.arange(x)
x2= np.arange(x)

#listtime
start =time.time()
res1 = [(a,b) for a,b in zip(l1,l2)]
print("List time req: "+str((time.time()-start)*1000))

start =time.time()
res2=x1+x2
print("Numpy arr time req: "+str((time.time()-start)*1000))

List time req: 94.36726570129395
Numpy arr time req: 0.7812976837158203


In [12]:
#list vs Numpy array
#calculate BMI = w/h*h
h = [72,58,65,40]
w = [170,100,200,136]
#will show an error unsupported operand type(s)
#bmi1 = w/h**2
print(h*2)

nh_in_inch = np.array(h)*0.0254
nw_in_kg = np.array(w)*0.453
bmi2 = nw_in_kg/nh_in_inch**2
print(bmi2)
# nh_in_inch*2

[72, 58, 65, 40, 72, 58, 65, 40]
[23.02579837 20.87251499 33.2379363  59.68286937]


In [151]:
#numpy array contains 1 datatype
print(np.array([1,11.5,"Hi",True])) #converted everything to string
print(np.array([1,11.5,True])) #converted everything to float
print(np.array([1,11.5]))   #converted everything to float

['1' '11.5' 'Hi' 'True']
[ 1.  11.5  1. ]
[ 1.  11.5]


In [152]:
#adding
list = [1,2,3,4]
print(list+list)

narr = np.array([1,2,3,4])
print(narr + narr)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [153]:
#subsetting
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])
print(arr[1:4]) #2nd element is exclusive [inclusive:exclusive]
print(arr[2:])
print(arr[:-2])


print(arr<4)
print(arr[arr<4]) #values

1
6
[2 3 4]
[3 4 5 6]
[1 2 3 4]
[ True  True  True False False False]
[1 2 3]


In [154]:
#type of numpy arr
arr = np.array([1,2,3,4,5,6])
l1 = [1,2,3]
l2 = range(6)
print(type(arr))
print(type(l1))
print(type(l2))

<class 'numpy.ndarray'>
<class 'list'>
<class 'range'>


In [155]:
#2D Array

In [14]:
arr1 = [[200,80],
        [250,75],
        [180,25],
        [188,15.4]]
np_arr1 = np.array(arr1)         
print(np_arr1)   #everything converted to float
print("-------------------")
print(type(np_arr1))
print("-------------------")
print(np_arr1.shape)  #row,col
print(len(np_arr1)) #row
range(len(np_arr1)) #2nd element is exclusive

[[200.   80. ]
 [250.   75. ]
 [180.   25. ]
 [188.   15.4]]
-------------------
<class 'numpy.ndarray'>
-------------------
(4, 2)
4


range(0, 4)

In [157]:
#subsetting [row][col]
print(np_arr1[0])
print(np_arr1[0][1])
print(type(np_arr1[0][1]))
print("-------------------")
#subsetting [row,col]
# : represents all row, col
print(np_arr1[:,1]) #all row 2nd col
print(np_arr1[2,:]) #3rd row all col
print("-------------------")
print(np_arr1[0:,1]) 
print(np_arr1[1:,1]) 

[200.  80.]
80.0
<class 'numpy.float64'>
-------------------
[80.  75.  25.  15.4]
[180.  25.]
-------------------
[80.  75.  25.  15.4]
[75.  25.  15.4]


In [8]:
#basic stats
arr1 = [[200,80],
        [250,75],
        [180,25],
        [188,15.4]]
np_arr1 = np.array(arr1) 
print(np_arr1)
#mean
print("Mean = "+str(np.mean(np_arr1[:,0])))  #all row 1st col
print("-------------------")
#median 
print("Median = "+str(np.median(np_arr1[:,0]))) ##all row 1st col

print("-------------------")
#correlation / o/p matrix
#near 0 ~ correlated to each other
#far from 0 ~ less correlated
print("Correlation = ")
print(np_arr1[:,0])
print(np_arr1[:,1])
print(np.corrcoef(np_arr1[:,0],np_arr1[:,1]))

#std deviation
print("Std Dev = "+str(np.std(np_arr1[:,0])))

[[200.   80. ]
 [250.   75. ]
 [180.   25. ]
 [188.   15.4]]
Mean = 204.5
-------------------
Median = 194.0
-------------------
Correlation = 
[200. 250. 180. 188.]
[80.  75.  25.  15.4]
[[1.         0.69465584]
 [0.69465584 1.        ]]
Std Dev = 27.216722800513658


In [212]:
#Adding 2D
a=[[1,2,3],
   [4,5,6],
   [7,8,9]]
na=np.array(a)
b=[[1,2,3],
   [4,5,6],
   [7,8,9]]
nb=np.array(b)

print("Addition")
c=na+nb
print(c)

print("-------------------")
print("Subtraction")
d=np.subtract(a1,b1)
print(d)

print("-------------------")
print("Division")
e=np.divide(a1,b1)
print(e)

print("-------------------")
print("Multiplication")
f=np.multiply(a1,b1)
print(f)

print("-------------------")
print("Square Root")
g=np.sqrt(a1)
print(g)


Addition
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-------------------
Subtraction
[[0 0 0 0]
 [0 0 0 0]]
-------------------
Division
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-------------------
Multiplication
[[ 1  4  9 16]
 [25 36 49 64]]
-------------------
Square Root
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [183]:
#multiply
# mul=[1,2,3]
mul=[0.5,0.2,1]
mulc=c*mul
mulc

array([[ 1. ,  0.8,  6. ],
       [ 4. ,  2. , 12. ],
       [ 7. ,  3.2, 18. ]])

In [221]:
#concatinate numpy array
a1 =  np.array([(1,2,3,4),(5,6,7,8)])
print(a1)
print("-------------------")
b1 =  np.array([(1,2,3,4),(5,6,7,8)])
print(b1)
print("-------------------")

#Vertical stack
print("Vertical")
print(np.vstack((a1,b1)))
print("-------------------")
#Horizontal stack
print("Horizontal")
print(np.hstack((a1,b1)))

[[1 2 3 4]
 [5 6 7 8]]
-------------------
[[1 2 3 4]
 [5 6 7 8]]
-------------------
Vertical
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
-------------------
Horizontal
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


In [222]:
#Other Basic Operations(Functions)
print("Minimun ="+str(a1.min()))
print("Minimun np ="+str(np.min(a1)))
print("-------------------")

print("Maximun ="+str(a1.max()))
print("Maximum np ="+str(np.max(a1)))
print("-------------------")

print("Variance ="+str(a1.var()))
print("Ravel ="+str(a1.ravel()))
print("-------------------")

print("Sum ="+str(a1.sum()))
print("Sum np="+str(np.sum(a1)))
print("Sum col np ="+str(np.sum(a1,axis=0)))
print("Sum row np ="+str(np.sum(a1,axis=1)))

Minimun =1
Minimun np =1
-------------------
Maximun =8
Maximum np =8
-------------------
Variance =5.25
Ravel =[1 2 3 4 5 6 7 8]
-------------------
Sum =36
Sum np=36
Sum col np =[ 6  8 10 12]
Sum row np =[10 26]


In [209]:
a = np.zeros((2,2)) 
print("Array of Zeros")
print(a) 
print("-------------------")

b = np.ones((2,2))  
print("Array of Ones")
print(b)
print("-------------------")

c = np.full((2,2), 7)
print("Array of Constant Value")
print(c)  
print("-------------------")

print("Identity Matrix")
d = np.eye(2)
print(d)
print("-------------------")

print("Random Value Matrix")
e = np.random.random((2,2))
print(e)

Array of Zeros
[[0. 0.]
 [0. 0.]]
-------------------
Array of Ones
[[1. 1.]
 [1. 1.]]
-------------------
Array of Constant Value
[[7 7]
 [7 7]]
-------------------
Identity Matrix
[[1. 0.]
 [0. 1.]]
-------------------
Random Value Matrix
[[0.47081986 0.19650214]
 [0.79452455 0.45320874]]
